### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by maulikmadhavi** [RasaHQ/DIET-paper#1]
May I get the link of this paper?

Thanks

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by dakshvar22** [comment]
@maulikmadhavi Here is an [arxiv](https://arxiv.org/abs/2004.09936) link for it.
