### ISSUE TITLE
Installation problem due to tensorflow

### ISSUE THREAD

**Issue by kmanwar** [RasaHQ/DIET-paper#2]
I am trying to reproduce the DIET paper by following their installation instructions given in GitHub - RasaHQ/DIET-paper: 

But I am facing problem with tensorflow version issue. Here is the error I am facing when I run the command: make install-full

Updating tensorflow (2.2.0 -> 2.1.0)
[EnvCommandError] Command [’/mnt/c/rasa/rasa/venv/bin/pip’, ‘install’, ‘–no-deps’, ‘-U’, ‘tensorflow==2.1.0’] errored with the following return code 1, and output: ERROR: Could not find a version that satisfies the requirement tensorflow==2.1.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0) ERROR: No matching distribution found for tensorflow==2.1.0

make: *** [Makefile:44: install] Error 1

Can you please suggest how to solve this issue?

I am using ubuntu in WSL2 under Windows 10.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hey @kmanwar what python version are you on?

**Comment by kmanwar** [comment]
Python 3.8.2

**Comment by akelad** [comment]
Please downgrade to 3.7, 3.8 isn't supported yet

**Comment by kmanwar** [comment]
Thanks.. I could install after downgrading.

But when I run the script following the instrcution, I got this error: 
./run.sh [table-1|table-2|table-3|table-4|table-5]
find: ‘configs/[table-1’: No such file or directory
find: ‘configs/[table-1’: No such file or directory
-bash: table-3: command not found
-bash: table-4: command not found
-bash: table-5]: command not found
-bash: table-2: command not found

**Comment by tabergma** [comment]
What command did you execute? You need to decide for one table, e.g. 
```
./run.sh table-1
```

**Comment by kmanwar** [comment]
It works for 1 table.

I executed before: ./run.sh [table-1|table-2|table-3|table-4|table-5]
