### ISSUE TITLE
Keep getting error: FileNotFoundError: [Errno 2] No such file or directory: 'results/diet-paper-eval.json'

### ISSUE THREAD

**Issue by nathan-chappell** [RasaHQ/DIET-paper#3]
I don't know if I messed up when installing it, but it wouldn't install directly.  When I tried to install rasa from the diet-paper branch, poetry kept complaining about a rasabaster dev dependency.  I ended up deleting the lock file, and then installing it.  Everything seemed to go okay.  Then I went to run the experiments, and this error keeps appearing.  When I look at the log files, there seems to be an issue with this:

>Downloading TF-Hub Module 'http://models.poly-ai.com/convert/v1/model.tar.gz'.

This is ends up not working.  The url is now dead, so I wonder if there was some model you were previously using that is no longer available.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by dakshvar22** [comment]
Hi @nathan-chappell Yes, you are right. The ConveRT model [was taken offline very recently](https://github.com/RasaHQ/rasa/issues/6806). As a result, you will not be able to reproduce these results on your side anymore.  You should still be able to reproduce results for pipelines which do not use the ConveRT model.

**Comment by nathan-chappell** [comment]
@dakshvar22  Thanks.  I was just trying to do some due-diligence, it seems like some of the tests are in face working, and some just error out.  Thanks for looking into it - I'll go ahead and mark this as closed.

**Comment by robertanto** [comment]
Dear authors,

I run in Rasa 2.6.2 your project and I successfully computed Intent and Entity scores with `rasa test`.
Unfortunately, I am not able to generate the file `diet-paper-eval.json` to compute the entity score at entity level (as you know, rasa computes performance at token level).

May you help me in reproducing your results?

Thank you in advance!
